Revert "ci: workaround registry.gitlab.com issues"
This reverts commit c5f218527615eefac53b7bb202b89b3b09cf1885 as the
workaround was not fully working, the runner was able to download the
container image, but then got banned by the host serving the artifacts:

 Downloading artifacts for generate (4302834381)...
 ERROR: Downloading artifacts from coordinator... forbidden  id=4302834381 responseStatus=403 Forbidden status=403 Forbidden token=64_bkzMh
 FATAL: permission denied

References: PCF-777
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 0d242e8b09341b17ee83fc1ada1021eb57f4130c)