owsd: fix compilation issue with libwebsockets version 4.x
Fix following compilation issue with libwebsockets version 4.x:

 owsd-1.1.4/src/main.c:552:17: error: 'struct lws_context_creation_info' has no member named 'ws_ping_pong_interval'
  552 |         lws_info.ws_ping_pong_interval = 300;
      |

By backporting upstream fix released in commit e37c6f9d708c ("Fix compilation issue with lws-4").

References: https://dev.iopsys.eu/iopsys/owsd/-/commit/e37c6f9d708
Signed-off-by: Petr Štetiar <ynezz@true.cz>