amxo-cg: workaround compile error with libxml2 version
amxo-cg compiles fine with OpenWrt 19.07 which uses libxml2 version
2.9.14, but it fails to compile with OpenWrt 22.03 which uses libxml2
version 2.10.2.

libxml2 since version v2.10.0 in commit 40483d0ce26 ("Deprecate module
init and cleanup functions") has deprecated certain API functions which
leads to following compiler error:

  xml/gen_xml.c: In function 'gen_xml_close':
  xml/gen_xml.c:167:5: error: 'xmlCleanupGlobals' is deprecated [-Werror=deprecated-declarations]
   167 |     xmlCleanupGlobals();
       |     ^~~~~~~~~~~~~~~~~
  In file included from /target-x86_64_musl/usr/include/libxml2/libxml/xmlIO.h:117,
                   from /target-x86_64_musl/usr/include/libxml2/libxml/parser.h:811,
                   from ../include_priv/gen_xml.h:80,
                   from xml/gen_xml.c:66:
  /target-x86_64_musl/usr/include/libxml2/libxml/globals.h:30:24: note: declared here
     30 | XMLPUBFUN void XMLCALL xmlCleanupGlobals(void);
        |                        ^~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

So lets workaround it by allowing the use of those deprecated, but still
available APIs.

References: PCF-736
References: https://github.com/GNOME/libxml2/commit/40483d0ce26119fd3b23aea6cce532a8a78670cf
Signed-off-by: Petr Štetiar <ynezz@true.cz>