amxo-cg: fix amxo_libversion API change in libamxo
libamxo in commit 382eb85a4a8f ("Issue: #71 Cannot load unknown instance parameter
with "populate-behavior.unknown-parameter=add" [fix]") changed API of
`amxo_lib_version()` to `amxo_libversion()` and thus now `amxo-cg` fails to compile:

 ocg_user_output.c: In function 'ocg_usage':
 ocg_user_output.c:120:57: error: implicit declaration of function 'amxo_lib_version'; did you mean 'amxo_libversion'? [-Werror=implicit-function-declaration]
             VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, amxo_lib_version());
                                                         ^~~~~~~~~~~~~~~~
                                                         amxo_libversion

So fix it by renaming that API call to a changed function name.

References: https://gitlab.com/prpl-foundation/prplos/feed-prpl/-/jobs/2056547406#L7431
Rererences: https://gitlab.com/prpl-foundation/components/ambiorix/applications/amxo-cg/-/merge_requests/1
Signed-off-by: Petr Štetiar <ynezz@true.cz>