netdev-plugin: fix missing libmnl dependency
Fixes following build error:

 netdev_bridgetable.c:68:10: fatal error: libmnl/libmnl.h: No such file or directory
 #include <libmnl/libmnl.h>
          ^~~~~~~~~~~~~~~~~

Signed-off-by: Petr Štetiar <ynezz@true.cz>