ci: exclude dslmngr and mcast-pa from build testing
Both packages can't be currently built with SDK and since they're not
being used in prplWrt it was decided to postpone the fixes for later.

dslmngr fails[1] with following:

 intel/intel_dsl_api.c:37:10: fatal error: drv_dsl_cpe_api/drv_dsl_cpe_api_ioctl.h: No such file or directory
  #include "drv_dsl_cpe_api/drv_dsl_cpe_api_ioctl.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mcast-pa fails[2] with following:

 mcast-pa.c:224:10: fatal error: kernel-list.h: No such file or directory
  #include <kernel-list.h>
           ^~~~~~~~~~~~~~~

1. https://gitlab.com/prpl-foundation/prplwrt/feed-prpl/-/jobs/860015716#L4277
2. https://gitlab.com/prpl-foundation/prplwrt/feed-prpl/-/jobs/860008676#L1181

Signed-off-by: Petr Štetiar <ynezz@true.cz>